2022-05-13 07:36:54,200 INFO    MainThread:8112 [wandb_setup.py:_flush():75] Loading settings from C:\Users\Aymen\.config\wandb\settings
2022-05-13 07:36:54,200 INFO    MainThread:8112 [wandb_setup.py:_flush():75] Loading settings from C:\Users\Aymen\Desktop\Neji\wandb\settings
2022-05-13 07:36:54,200 INFO    MainThread:8112 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-05-13 07:36:54,200 INFO    MainThread:8112 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-05-13 07:36:54,201 INFO    MainThread:8112 [wandb_setup.py:_flush():75] Applying settings from <Settings {'_args': None, '_cli_only_mode': None, '_colab': False, '_config_dict': None, '_console': <SettingsConsole.WRAP: 1>, '_cuda': None, '_disable_meta': None, '_disable_stats': None, '_disable_viewer': None, '_except_exit': None, '_executable': None, '_internal_check_process': 8, '_internal_queue_timeout': 2, '_jupyter': True, '_jupyter_name': None, '_jupyter_path': None, '_jupyter_root': None, '_kaggle': False, '_noop': False, '_offline': False, '_os': None, '_platform': 'windows', '_python': None, '_require_service': None, '_runqueue_item_id': None, '_save_requirements': True, '_service_transport': None, '_start_datetime': None, '_start_time': None, '_tmp_code_dir': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\tmp\\code', '_tracelog': None, '_unsaved_keys': None, '_windows': True, 'allow_val_change': None, 'anonymous': None, 'api_key': '***REDACTED***', 'base_url': 'https://api.wandb.ai', 'code_dir': None, 'config_paths': None, 'console': 'auto', 'deployment': 'cloud', 'disable_code': None, 'disable_git': None, 'disabled': False, 'docker': None, 'email': None, 'entity': None, 'files_dir': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\files', 'force': None, 'git_remote': 'origin', 'heartbeat_seconds': 30, 'host': None, 'ignore_globs': (), 'is_local': False, 'label_disable': None, 'launch': None, 'launch_config_path': None, 'log_dir': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\logs', 'log_internal': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\logs\\debug-internal.log', 'log_symlink_internal': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\debug-internal.log', 'log_symlink_user': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\debug.log', 'log_user': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\logs\\debug.log', 'login_timeout': None, 'magic': None, 'mode': 'online', 'notebook_name': None, 'problem': 'fatal', 'program': None, 'program_relpath': None, 'project': None, 'project_url': '', 'quiet': None, 'reinit': None, 'relogin': None, 'resume': None, 'resume_fname': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\wandb-resume.json', 'resumed': False, 'root_dir': 'C:\\Users\\Aymen\\Desktop\\Neji', 'run_group': None, 'run_id': None, 'run_job_type': None, 'run_mode': 'run', 'run_name': None, 'run_notes': None, 'run_tags': None, 'run_url': '', 'sagemaker_disable': None, 'save_code': None, 'settings_system': 'C:\\Users\\Aymen\\.config\\wandb\\settings', 'settings_workspace': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\settings', 'show_colors': None, 'show_emoji': None, 'show_errors': True, 'show_info': True, 'show_warnings': True, 'silent': False, 'start_method': 'thread', 'strict': None, 'summary_errors': None, 'summary_warnings': 5, 'sweep_id': None, 'sweep_param_path': None, 'sweep_url': '', 'symlink': None, 'sync_dir': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None', 'sync_file': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\run-None.wandb', 'sync_symlink_latest': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\latest-run', 'system_sample': 15, 'system_sample_seconds': 2, 'timespec': None, 'tmp_dir': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\run-None-None\\tmp', 'username': None, 'wandb_dir': 'C:\\Users\\Aymen\\Desktop\\Neji\\wandb\\'}>
2022-05-13 07:36:54,202 INFO    MainThread:8112 [wandb_init.py:_log_setup():437] Logging user logs to C:\Users\Aymen\Desktop\Neji\wandb\run-20220513_073654-iaq1nkxb\logs\debug.log
2022-05-13 07:36:54,203 INFO    MainThread:8112 [wandb_init.py:_log_setup():438] Logging internal logs to C:\Users\Aymen\Desktop\Neji\wandb\run-20220513_073654-iaq1nkxb\logs\debug-internal.log
2022-05-13 07:36:54,203 INFO    MainThread:8112 [wandb_init.py:init():471] calling init triggers
2022-05-13 07:36:54,203 INFO    MainThread:8112 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {}
2022-05-13 07:36:54,203 INFO    MainThread:8112 [wandb_init.py:init():491] re-initializing run, found existing run on stack: 3iwlc4jb
2022-05-13 07:36:54,205 INFO    MainThread:8112 [wandb_run.py:_finish():1685] finishing run aymentlili/Music Genre Classification/3iwlc4jb
2022-05-13 07:36:54,205 INFO    MainThread:8112 [jupyter.py:save_history():435] not saving jupyter history
2022-05-13 07:36:54,206 INFO    MainThread:8112 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-05-13 07:36:54,206 INFO    MainThread:8112 [wandb_init.py:_jupyter_teardown():369] cleaning up jupyter logic
2022-05-13 07:36:54,206 INFO    MainThread:8112 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 0
2022-05-13 07:36:54,207 INFO    MainThread:8112 [wandb_run.py:_restore():1838] restore
2022-05-13 07:36:55,137 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 672
}

2022-05-13 07:37:00,253 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: None
2022-05-13 07:37:01,768 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 672
}

2022-05-13 07:37:01,956 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 18710
}

2022-05-13 07:37:02,056 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 18739
}

2022-05-13 07:37:02,168 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 18739
}

2022-05-13 07:37:02,277 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 18739
}

2022-05-13 07:37:02,387 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 18739
}

2022-05-13 07:37:02,496 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 672
  total_bytes: 18739
}

2022-05-13 07:37:02,605 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:02,719 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:02,828 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:02,938 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:03,047 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:03,156 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:03,266 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:04,016 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}

2022-05-13 07:37:04,922 INFO    MainThread:8112 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18739
  total_bytes: 18739
}
local_info {
}

2022-05-13 07:37:17,212 INFO    MainThread:8112 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-05-13 07:37:17,212 INFO    MainThread:8112 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-05-13 07:37:17,258 INFO    MainThread:8112 [wandb_run.py:_footer_sync_info():3057] logging synced files
2022-05-13 07:37:17,273 INFO    MainThread:8112 [wandb_init.py:init():524] starting backend
2022-05-13 07:37:17,273 INFO    MainThread:8112 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-05-13 07:37:17,278 INFO    MainThread:8112 [backend.py:ensure_launched():217] starting backend process...
2022-05-13 07:37:21,511 INFO    MainThread:8112 [backend.py:ensure_launched():222] started backend process with pid: 9660
2022-05-13 07:37:21,543 INFO    MainThread:8112 [wandb_init.py:init():533] backend started and connected
2022-05-13 07:37:21,558 INFO    MainThread:8112 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-05-13 07:37:21,558 INFO    MainThread:8112 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-05-13 07:37:21,558 INFO    MainThread:8112 [wandb_init.py:init():597] updated telemetry
2022-05-13 07:37:21,620 INFO    MainThread:8112 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-05-13 07:37:51,636 INFO    MainThread:8112 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-05-13 07:37:51,636 ERROR   MainThread:8112 [wandb_init.py:init():633] backend process timed out
2022-05-13 07:37:51,636 ERROR   MainThread:8112 [wandb_init.py:init():644] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-05-13 07:38:26,845 INFO    MainThread:8112 [wandb_init.py:teardown():285] tearing down wandb.init
